// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/2022/08/how-to-make-switchbot-products-compatible-with-homekit.html": {
    params: {};
  };
  "/2022/08/how-to-install-home-assistant-on-virtualbox.html": {
    params: {};
  };
  "/2021/11/used-mac-how-to-choice-guide-2022.html": {
    params: {};
  };
  "/2022/09/used-mac-how-to-choice-guide-2023.html": {
    params: {};
  };
  "/2022/07/apple-accessibility-settings.html": {
    params: {};
  };
  "/2022/05/how-to-use-idevice-with-xac.html": {
    params: {};
  };
  "/2023/03/what-is-matter-and-thread.html": {
    params: {};
  };
  "/2022/10/nreal-air-using-with-mac.html": {
    params: {};
  };
  "/2022/11/apple-tv-4k-2022-review.html": {
    params: {};
  };
  "/2022/12/using-lg-tv-with-voice.html": {
    params: {};
  };
  "/2022/06/nreal-air-review.html": {
    params: {};
  };
  "/p/blog-page_10.html": {
    params: {};
  };
  "/p/blog-page_6.html": {
    params: {};
  };
  "/p/blog-page_7.html": {
    params: {};
  };
  "/p/blog-page.html": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/page/:slug": {
    params: {
      "slug": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/2022/08/how-to-make-switchbot-products-compatible-with-homekit.html" | "/2022/08/how-to-install-home-assistant-on-virtualbox.html" | "/2021/11/used-mac-how-to-choice-guide-2022.html" | "/2022/09/used-mac-how-to-choice-guide-2023.html" | "/2022/07/apple-accessibility-settings.html" | "/2022/05/how-to-use-idevice-with-xac.html" | "/2023/03/what-is-matter-and-thread.html" | "/2022/10/nreal-air-using-with-mac.html" | "/2022/11/apple-tv-4k-2022-review.html" | "/2022/12/using-lg-tv-with-voice.html" | "/2022/06/nreal-air-review.html" | "/p/blog-page_10.html" | "/p/blog-page_6.html" | "/p/blog-page_7.html" | "/p/blog-page.html" | "/sitemap.xml" | "/blog/:slug" | "/page/:slug" | "/robots.txt" | "/_image/*" | "/*";
  };
  "routes/[2022].[08].[how-to-make-switchbot-products-compatible-with-homekit.html]._index.ts": {
    id: "routes/[2022].[08].[how-to-make-switchbot-products-compatible-with-homekit.html]._index";
    page: "/2022/08/how-to-make-switchbot-products-compatible-with-homekit.html";
  };
  "routes/[2022].[08].[how-to-install-home-assistant-on-virtualbox.html]._index.ts": {
    id: "routes/[2022].[08].[how-to-install-home-assistant-on-virtualbox.html]._index";
    page: "/2022/08/how-to-install-home-assistant-on-virtualbox.html";
  };
  "routes/[2021].[11].[used-mac-how-to-choice-guide-2022.html]._index.ts": {
    id: "routes/[2021].[11].[used-mac-how-to-choice-guide-2022.html]._index";
    page: "/2021/11/used-mac-how-to-choice-guide-2022.html";
  };
  "routes/[2022].[09].[used-mac-how-to-choice-guide-2023.html]._index.ts": {
    id: "routes/[2022].[09].[used-mac-how-to-choice-guide-2023.html]._index";
    page: "/2022/09/used-mac-how-to-choice-guide-2023.html";
  };
  "routes/[2022].[07].[apple-accessibility-settings.html]._index.ts": {
    id: "routes/[2022].[07].[apple-accessibility-settings.html]._index";
    page: "/2022/07/apple-accessibility-settings.html";
  };
  "routes/[2022].[05].[how-to-use-idevice-with-xac.html]._index.ts": {
    id: "routes/[2022].[05].[how-to-use-idevice-with-xac.html]._index";
    page: "/2022/05/how-to-use-idevice-with-xac.html";
  };
  "routes/[2023].[03].[what-is-matter-and-thread.html]._index.ts": {
    id: "routes/[2023].[03].[what-is-matter-and-thread.html]._index";
    page: "/2023/03/what-is-matter-and-thread.html";
  };
  "routes/[2022].[10].[nreal-air-using-with-mac.html]._index.ts": {
    id: "routes/[2022].[10].[nreal-air-using-with-mac.html]._index";
    page: "/2022/10/nreal-air-using-with-mac.html";
  };
  "routes/[2022].[11].[apple-tv-4k-2022-review.html]._index.ts": {
    id: "routes/[2022].[11].[apple-tv-4k-2022-review.html]._index";
    page: "/2022/11/apple-tv-4k-2022-review.html";
  };
  "routes/[2022].[12].[using-lg-tv-with-voice.html]._index.ts": {
    id: "routes/[2022].[12].[using-lg-tv-with-voice.html]._index";
    page: "/2022/12/using-lg-tv-with-voice.html";
  };
  "routes/[2022].[06].[nreal-air-review.html]._index.ts": {
    id: "routes/[2022].[06].[nreal-air-review.html]._index";
    page: "/2022/06/nreal-air-review.html";
  };
  "routes/[p].[blog-page_10.html]._index.ts": {
    id: "routes/[p].[blog-page_10.html]._index";
    page: "/p/blog-page_10.html";
  };
  "routes/[p].[blog-page_6.html]._index.ts": {
    id: "routes/[p].[blog-page_6.html]._index";
    page: "/p/blog-page_6.html";
  };
  "routes/[p].[blog-page_7.html]._index.ts": {
    id: "routes/[p].[blog-page_7.html]._index";
    page: "/p/blog-page_7.html";
  };
  "routes/[p].[blog-page.html]._index.ts": {
    id: "routes/[p].[blog-page.html]._index";
    page: "/p/blog-page.html";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[blog].$slug._index.tsx": {
    id: "routes/[blog].$slug._index";
    page: "/blog/:slug";
  };
  "routes/[page].$slug._index.tsx": {
    id: "routes/[page].$slug._index";
    page: "/page/:slug";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};